### PR TITLE
Add Scenegraph support

### PR DESCRIPTION
**Pull request by PixelDust22**
In #17 @Sixmorphugus created the implementation for adding scenegraph support. I've forked his code and opened a PR on his behalf so we can start a review.

### CODE REVIEW

**Comment by virtualritz** [comment]
I suggest merging this first, then #22, after @nickelc has added `nom` 7 support to `scene.rs`. And #24 last.

**Review by davidedmonds — APPROVED** [review]

**Comment by nickelc** [comment]
@Neo-Zhixing Could you fix the tests, please? It's blocking the rebase of #22.
```
error[E0063]: missing fields `layers` and `scene` in initializer of `dot_vox_data::DotVoxData`
   --> src/lib.rs:189:9
    |
189 |         DotVoxData {
    |         ^^^^^^^^^^ missing `layers` and `scene`
```

**Comment by PixelDust22** [comment]
@nickelc  will do!

**Comment by PixelDust22** [comment]
@nickelc Tests fixed

**Pull request merged**
