### PR TITLE
AHash feature, Rust edition 2021, cargo fmt

### PR DESCRIPTION
**Pull request by virtualritz**
* Added optional [`ahash`](https://crates.io/crates/ahash) dependency for faster hashing/lookups.
* Bumped code to Rust 2021.
* ran `cargo fmt`.

### CODE REVIEW

**Comment by virtualritz** [comment]
I suggest to apply this PR last, after the other two. Should lead to less conflicts.

**Comment by virtualritz** [comment]
As it's been a month: is there anything I or others could do to help getting the open PRs accepted and an updated version of the crate published?

**Comment by davidedmonds** [comment]
Hey - sorry for the lack of merging - have merged the first of the three PRs, which should hopefully get these unblocked.

**Comment by virtualritz** [comment]
Ok, if there are still conflicts after applying the 2nd PR I'll try to fix them.

**Comment by davidedmonds** [comment]
Wasn't entirely sure if this got rolled into #27 in the end - closing assuming it has, but if there's still outstanding work feel free to reopen.

**Comment by virtualritz** [comment]
The `AHash` feature fell through the cracks of the downstream merges, I'm afraid.

**Comment by virtualritz** [comment]
I'll open another PR once I find some time.

**Pull request closed without merging**
